name: Deploy JBbot (Auto Fail Test)
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Fail Test
        run: |
          echo "❌ Deployment test failed intentionally!"
          echo "Webhook should receive failure notification"
          exit 1
